
CREATE INDEX "CRM_XXCUST"."CRM_MSG_RECORD_ID_IDX1" ON "CRM_XXCUST"."RESUBMISSION_PROCESS_TAB" ("MESSAGE_RECORD_ID") TABLESPACE "CRM_XXCUST_DATA";
CREATE INDEX "CRM_XXCUST"."CRM_MSG_RECORD_ID_IDX2" ON "CRM_XXCUST"."RESUBMISSION_TAB" ("MESSAGE_RECORD_ID") TABLESPACE "CRM_XXCUST_DATA";
CREATE INDEX "CRM_XXCUST"."CRM_MSG_RECORD_ID_IDX3" ON "CRM_XXCUST"."EXCEPTION_LOGGING_TAB" ("MESSAGE_RECORD_ID") TABLESPACE "CRM_XXCUST_DATA";
CREATE INDEX "CRM_XXCUST"."CRM_MSG_RECORD_ID_IDX4" ON "CRM_XXCUST"."MESSAGE_LOGGING_PAYLOAD_TAB" ("MESSAGE_RECORD_ID") TABLESPACE "CRM_XXCUST_DATA";
CREATE INDEX "WAM_XXCUST"."WAM_MSG_RECORD_ID_IDX1" ON "WAM_XXCUST"."RESUBMISSION_PROCESS_TAB" ("MESSAGE_RECORD_ID") TABLESPACE "WAM_XXCUST_IND";
CREATE INDEX "WAM_XXCUST"."WAM_MSG_RECORD_ID_IDX2" ON "WAM_XXCUST"."RESUBMISSION_TAB" ("MESSAGE_RECORD_ID") TABLESPACE "WAM_XXCUST_IND";
CREATE INDEX "WAM_XXCUST"."WAM_MSG_RECORD_ID_IDX3" ON "WAM_XXCUST"."EXCEPTION_LOGGING_TAB" ("MESSAGE_RECORD_ID") TABLESPACE "WAM_XXCUST_IND";
CREATE INDEX "WAM_XXCUST"."WAM_MSG_RECORD_ID_IDX4" ON "WAM_XXCUST"."MESSAGE_LOGGING_PAYLOAD_TAB" ("MESSAGE_RECORD_ID") TABLESPACE "WAM_XXCUST_IND";
CREATE INDEX "SSE_XXCUST"."SSE_MSG_RECORD_ID_IDX1" ON "SSE_XXCUST"."RESUBMISSION_PROCESS_TAB" ("MESSAGE_RECORD_ID") TABLESPACE "SSE_XXCUST_INDEX";
CREATE INDEX "SSE_XXCUST"."SSE_MSG_RECORD_ID_IDX2" ON "SSE_XXCUST"."RESUBMISSION_TAB" ("MESSAGE_RECORD_ID") TABLESPACE "SSE_XXCUST_INDEX";
CREATE INDEX "SSE_XXCUST"."SSE_MSG_RECORD_ID_IDX3" ON "SSE_XXCUST"."EXCEPTION_LOGGING_TAB" ("MESSAGE_RECORD_ID") TABLESPACE "SSE_XXCUST_INDEX";
CREATE INDEX "SSE_XXCUST"."SSE_MSG_RECORD_ID_IDX4" ON "SSE_XXCUST"."MESSAGE_LOGGING_PAYLOAD_TAB" ("MESSAGE_RECORD_ID") TABLESPACE "SSE_XXCUST_INDEX";
