package main

import (
	"fmt"
	"strings"
)

// render_detailed.go — direct port of render_detailed() and its
// _render_*_detailed() helpers from gen_release_plan.py. Every object is
// spelled out individually — no "repeat this procedure for each row" step.

func renderDetailed(e *Export, domain, env string) string {
	infra := e.Infrastructure
	dsList := infra.JdbcDataSources
	stores := infra.PersistentStores
	fStores := fileStores(e)
	jStores := jdbcStores(e)
	jmsServers := infra.JmsServers
	safAgents := e.SafAgents
	modules := e.JmsModules
	adapters := e.AdapterDeployments
	targetNames := infraTargetNames(e)
	extDeps := externalStoreDependencies(e)
	untargeted := untargetedSafAgents(e)
	extDepNames := extDepNamesOnly(extDeps)

	b := &builder{}
	a := b.a
	af := b.af

	a("# Release Plan (Detailed, Step-by-Step) — SOA Suite Domain JMS / " +
		"Infrastructure Rebuild\n")
	af("**Domain / Environment:** `%s` / `%s`", domain, env)
	a("**Audience:** this version assumes no familiarity with this " +
		"specific migration.\nEvery object is written out individually — " +
		"there is no \"repeat this procedure\nfor each row\" step. Work top " +
		"to bottom, tick each box, do not skip ahead.\n")
	af("**Source of values:** `export.json` (generated by "+
		"`extract_objects.py`), domain\n`%s` / environment `%s`.", domain, env)
	a("**Target:** WebLogic Admin Console (manual, click-through " +
		"deployment).")
	a("**Companion file:** `release-plan.md` in this same folder is the " +
		"condensed\nversion of this plan (procedures + lookup tables).")
	a("**Generated by:** `gorelease` (Go port of `extract/gen_release_plan.py`) — re-run against a " +
		"fresh export if\nthe source domain's config changes; do not hand-" +
		"edit this file, edit the export\nor the generator instead.\n")
	a("---\n")

	a("## 0. Before You Start\n")
	a("- [ ] You have the Admin Console URL and an admin login for the " +
		"**target**\n      domain.")
	af("- [ ] You know whether the target domain's server/cluster names "+
		"match the\n      source domain's names exactly. The source names "+
		"used throughout this\n      plan are: %s. **If your target uses "+
		"different names, substitute your\n      names everywhere this plan "+
		"says one of those names — object names\n      (data sources, "+
		"stores, queues, etc.) are NOT renamed, only these\n      "+
		"infrastructure names.**", joinBacktickNames(targetNames))
	if len(dsList) > 0 {
		af("- [ ] You have the %d database passwords for the data sources "+
			"in Phase 1\n      (from vault / DBA — none were exported from "+
			"the source domain).", len(dsList))
	}
	for _, dep := range extDeps {
		af("- [ ] You've confirmed `%s` already exists on the target domain "+
			"(referenced\n      by persistent store `%s` — this plan does "+
			"not create it).", dep.DSName, dep.StoreName)
	}
	if len(adapters) > 0 {
		af("- [ ] The %d adapter `.rar` files and %d deployment plan `.xml` "+
			"files (Phase 6)\n      are staged somewhere the target Admin "+
			"Server can read them.", len(adapters), len(adapters))
	}
	a("- [ ] You've taken a config backup / snapshot of the target " +
		"domain.")
	a("- [ ] **This plan is out of scope for:** SOA composites, OSB " +
		"projects, and\n      any system/internal WebLogic objects that " +
		"come from the domain\n      template or product install.\n")
	a("---\n")

	a("## 1. Starting an Edit Session\n")
	a("Do this once now, and again at the start of every Phase below (a " +
		"Phase always\nends with **Activate Changes**, which closes the " +
		"session).\n")
	a("1. [ ] Open a browser to the target Admin Console, e.g.\n       " +
		"`http://<admin-host>:<port>/console`.")
	a("2. [ ] Log in with the admin account.")
	a("3. [ ] Top-left corner: find the **Change Center** panel.")
	a("4. [ ] Click **Lock & Edit**. The console now shows you are in an " +
		"edit\n       session — everything you do below is staged, not " +
		"live, until you\n       activate it.\n")
	a("**At the end of each Phase** (marked with a ➡ in this document):\n")
	a("5. [ ] Click **Activate Changes** in the Change Center.")
	a("6. [ ] If the console reports errors for that phase, click **Undo " +
		"All\n       Changes**, fix the problem, and start that phase's " +
		"steps again from\n       Lock & Edit.")
	a("7. [ ] If it succeeds, move to the next Phase and start a fresh " +
		"Lock & Edit.\n")
	a("Do not activate mid-phase — a partially-created phase can leave " +
		"dangling\nreferences.\n")
	a("---\n")

	a("## 2. Order of Work\n")
	a("Do the phases strictly in this order. Each later phase references " +
		"objects\ncreated in an earlier one.\n")
	af("1. Phase 1 — %d JDBC Data Sources", len(dsList))
	af("2. Phase 2 — %d Persistent Stores (%d File Stores + %d JDBC "+
		"Stores)", len(stores), len(fStores), len(jStores))
	af("3. Phase 3 — %d JMS Servers", len(jmsServers))
	af("4. Phase 4 — %d SAF Agents", len(safAgents))
	af("5. Phase 5 — %d JMS Modules (with their subdeployments, queues, "+
		"connection\n   factories, and SAF error handlings)", len(modules))
	if len(adapters) > 0 {
		af("6. Phase 6 — %d Adapter Deployments", len(adapters))
	}
	a("")
	a("---\n")

	// ---- PHASE 1 ----
	a("# PHASE 1 — JDBC Data Sources\n")
	a("Start a fresh **Lock & Edit** session (§1) before object 1.1 " +
		"below.\n")
	a("For every data source in this phase you will do the same six-page " +
		"wizard,\nthen a post-creation step to overwrite three fields the " +
		"wizard doesn't set\ncorrectly (URL, Driver Class Name, Properties) " +
		"plus the password and pool\nsizing. This is deliberate — the " +
		"wizard's assembled values are not trusted;\nwhat you type in the " +
		"**Post-Step** for each object below is the value that\nmust end up " +
		"saved.\n")
	a("---\n")
	for i, ds := range dsList {
		a(renderDatasourceDetailed(i+1, ds))
	}
	a("---\n")
	a("## ➡ End of Phase 1\n")
	a("- [ ] Click **Activate Changes**.")
	af("- [ ] Verify: **Services → Data Sources** lists all %d: %s.",
		len(dsList), joinBacktickNamesFromDS(dsList))
	targetedDS := targetedDataSources(dsList)
	untargetedDS := untargetedDataSources(dsList)
	if len(targetedDS) > 0 {
		af("- [ ] For each of the %d **targeted** ones (%s), open it → "+
			"**Monitoring → Testing** tab → select a target server →\n      "+
			"click **Test Data Source**. Confirm success (this requires the\n"+
			"      password to be correct).",
			len(targetedDS), joinBacktickNamesFromDS(targetedDS))
	}
	if len(untargetedDS) > 0 {
		it := "it"
		they := "it"
		if len(untargetedDS) != 1 {
			it = "they"
			they = "they"
		}
		af("- [ ] %s untargeted, so %s cannot be tested this way — just "+
			"confirm %s appears in the list with the right URL.",
			joinBacktickNamesFromDS(untargetedDS), it, they)
	}
	a("\n---\n")

	// ---- PHASE 2 ----
	a("# PHASE 2 — Persistent Stores\n")
	a("Start a fresh **Lock & Edit** session before object 2.1.\n")
	af("There are two kinds: **File Stores** (data written to disk files) "+
		"and\n**JDBC Stores** (data written to a database table via a data "+
		"source). Do\nall %d file stores first, then all %d JDBC stores — "+
		"order between them\ndoesn't matter, but both must finish before "+
		"Phase 3.\n", len(fStores), len(jStores))
	a("---\n")
	counter := 1
	for _, fs := range fStores {
		a(renderFilestoreDetailed(2, counter, fs))
		counter++
	}
	for _, js := range jStores {
		a(renderJdbcstoreDetailed(2, counter, js, extDepNames[js.Name]))
		counter++
	}
	a("---\n")
	a("## ➡ End of Phase 2\n")
	a("- [ ] Click **Activate Changes**.")
	af("- [ ] Verify: **Services → Persistent Stores** lists all %d: the %d "+
		"file\n      stores (%s) and the %d JDBC stores (%s), each with the "+
		"target you set\n      above.\n",
		len(stores), len(fStores), joinBacktickNamesFromStores(fStores),
		len(jStores), joinBacktickNamesFromStores(jStores))
	a("---\n")

	// ---- PHASE 3 ----
	a("# PHASE 3 — JMS Servers\n")
	a("Start a fresh **Lock & Edit** session before object 3.1. Each JMS " +
		"server\nbelow references a persistent store created in Phase 2 — " +
		"Phase 2 must be\nactivated first.\n")
	for i, js := range jmsServers {
		af("## 3.%d JMS Server: `%s`\n", i+1, js.Name)
		a("1. [ ] Domain Structure → **Services → Messaging → JMS Servers " +
			"→ New**.")
		af("2. [ ] Name: `%s`.", js.Name)
		af("3. [ ] Persistent Store: `%s`. Click **Next**.", js.PersistentStore)
		af("4. [ ] Target: %s. Click **Finish**.", fmtTargets(js.Targets))
		a("5. [ ] Leave Bytes Maximum / Messages Maximum at their " +
			"unlimited defaults —\n       no change needed.\n")
	}
	a("---\n")
	a("## ➡ End of Phase 3\n")
	a("- [ ] Click **Activate Changes**.")
	af("- [ ] Verify: **Services → Messaging → JMS Servers** lists all %d: "+
		"%s — each\n      bound to the persistent store you set.",
		len(jmsServers), joinBacktickNamesFromJmsServers(jmsServers))
	a("- [ ] Check **Monitoring** tab for each — Health should read OK " +
		"once the\n      target server has restarted (or immediately if " +
		"this is a dynamic\n      cluster that doesn't require a restart).\n")
	a("---\n")

	// ---- PHASE 4 ----
	a("# PHASE 4 — SAF (Store-and-Forward) Agents\n")
	a("Start a fresh **Lock & Edit** session before object 4.1.\n")
	if len(safAgents) > 0 {
		s0 := safAgents[0]
		a("**Every agent below shares these common advanced settings — " +
			"set them on\neach agent after creating it, exactly as " +
			"listed:**")
		af("- Retry Delay Base: `%s` ms", pyInt(s0.RetryDelayBase))
		af("- Retry Delay Maximum: `%s` ms", pyInt(s0.RetryDelayMaximum))
		af("- Retry Multiplier: `%s`", pyInt(s0.RetryDelayMultiplier))
		af("- Acknowledge Interval: `%s` (this is the console default — "+
			"leave it alone)", pyInt(s0.AcknowledgeInterval))
		af("- Window Size: `%s`", pyInt(s0.WindowSize))
		af("- Time-To-Live: `%s` (unlimited)", pyInt(s0.TimeToLive))
		loggingState := "DISABLED"
		if s0.LoggingEnabled {
			loggingState = "ENABLED"
		}
		var loggingNote string
		if s0.LoggingEnabled {
			loggingNote = "this is not the console default (default is disabled) — every " +
				"one of the agents below must have logging turned ON."
		} else {
			loggingNote = "confirm this matches the console default before assuming no " +
				"action is needed."
		}
		af("- **Logging: %s** ⚠️ %s\n", loggingState, loggingNote)
	}
	for i, saf := range safAgents {
		af("## 4.%d SAF Agent: `%s`\n", i+1, saf.Name)
		a("1. [ ] Domain Structure → **Services → Messaging → " +
			"Store-and-Forward Agents\n       → New**.")
		af("2. [ ] Name: `%s`.", saf.Name)
		af("3. [ ] Persistent Store: `%s`.", saf.Store)
		note := SafServiceTypeNote[saf.ServiceType]
		if note != "" {
			af("4. [ ] Agent Type: **%s** (%s). Click **Next**.", saf.ServiceType, note)
		} else {
			af("4. [ ] Agent Type: **%s**. Click **Next**.", saf.ServiceType)
		}
		if len(saf.Targets) > 0 {
			af("5. [ ] Target: %s. Click **Finish**.", fmtTargets(saf.Targets))
		} else {
			a("5. [ ] Target: **tick nothing** — this agent is untargeted " +
				"on the source\n       domain. Click **Finish**.")
		}
		loggingWord := "DISABLED"
		if saf.LoggingEnabled {
			loggingWord = "ENABLED"
		}
		af("6. [ ] Open the agent → set the common settings listed above, "+
			"including\n       **Logging = %s**. Save.", loggingWord)
		if len(saf.Targets) == 0 {
			a("7. [ ] ⚠️ Note: leaving this untargeted matches the source, " +
				"but confirm\n       with the application owner before " +
				"go-live whether that's intended\n       or an oversight on " +
				"the source domain.")
		}
		a("")
	}
	a("---\n")
	a("## ➡ End of Phase 4\n")
	a("- [ ] Click **Activate Changes**.")
	af("- [ ] Verify: **Services → Messaging → Store-and-Forward Agents** "+
		"lists all %d:\n      %s.",
		len(safAgents), joinBacktickNamesFromSaf(safAgents))
	a("- [ ] Open each and confirm Logging matches the value noted above " +
		"— this is\n      easy to miss since it isn't always the console " +
		"default.\n")
	a("---\n")

	// ---- PHASE 5 ----
	a("# PHASE 5 — JMS Modules\n")
	a("Start a fresh **Lock & Edit** session before object 5.1. Each " +
		"module below\nis done completely (module → subdeployment(s) → " +
		"destinations/CFs/error\nhandlings) before moving to the next " +
		"module.\n")
	a("**General pattern for every module in this phase — the exact " +
		"wizard steps\nyou'll repeat, spelled out once here for reference. " +
		"Each module section\nbelow tells you exactly what values to type " +
		"at each of these steps; you\ndon't need to look anything up " +
		"elsewhere.**\n")
	a("- *Create the module itself:* **Services → Messaging → JMS Modules " +
		"→ New**\n  → type Name → Next → tick Targets → Next → Finish.")
	a("- *Add a subdeployment* (do this before adding any destination " +
		"that uses\n  it): open the module → **Subdeployments** tab → New " +
		"→ type Subdeployment\n  Name → Next → tick the Targets (a JMS " +
		"server, a SAF agent, or a cluster,\n  depending on the module) → " +
		"Finish.")
	a("- *Add a Queue / Topic:* open the module → New → select the " +
		"destination\n  type → Next → type Name and JNDI Name → Next → " +
		"select the Subdeployment\n  → Finish.")
	a("- *Add a Distributed Queue/Topic (Uniform or plain):* same as " +
		"above but\n  select the distributed variant → after Finish, open " +
		"it and set Load\n  Balancing Policy.")
	a("- *Add a Connection Factory (default-targeted):* open the module " +
		"→ New →\n  **Connection Factory** → Next → type Name and JNDI Name " +
		"→ Next → on the\n  Targeting page, **leave \"Default Targeting " +
		"Enabled\" checked and do not\n  select a Subdeployment** → " +
		"Finish.")
	a("- *Add a SAF Error Handling:* open the module → New → **SAF Error " +
		"Handling**\n  → Next → type Name → select Policy → Finish.\n")
	a("---\n")

	for i, mod := range modules {
		a(renderModuleDetailed(i+1, mod))
	}
	a("---\n")
	a("## ➡ End of Phase 5\n")
	a("- [ ] Click **Activate Changes**.")
	af("- [ ] Verify each of the %d modules lists its subdeployment(s) and "+
		"its\n      resources under **Services → Messaging → JMS Modules → "+
		"[module\n      name]**.", len(modules))
	defaultCFs := defaultTargetedCFs(modules)
	if len(defaultCFs) > 0 {
		af("- [ ] Verify the %d default-targeted connection factories\n      "+
			"(%s) each show **Default\n      Targeting** on their **Targets** "+
			"tab, with no subdeployment selected.",
			len(defaultCFs), joinBacktickNames(defaultCFs))
	}
	distNames := distributedDestinations(modules)
	for _, d := range distNames {
		af("- [ ] Verify `%s`'s Load Balancing Policy shows **%s**.", d.Name, d.Policy)
	}
	a("\n---\n")

	// ---- PHASE 6 ----
	if len(adapters) > 0 {
		a("# PHASE 6 — Adapter Deployments\n")
		a("Start a fresh **Lock & Edit** session before object 6.1. Every " +
			"JMS module\nfrom Phase 5 must exist before you deploy adapters " +
			"whose connection\ninstances reference JMS resources created " +
			"there.\n")
		a("⚠️ **Every connection instance listed below has " +
			"host/user/password/JNDI\ncredentials baked into its plan XML " +
			"that were not exported from the source\ndomain.** After each " +
			"adapter is redeployed, you must open its Outbound\nConnection " +
			"Pools and manually review/set these for the target environment\n" +
			"— the steps below tell you which connection instances to " +
			"check, not what\nvalues to put in them (get those from the " +
			"application owner / vault).\n")
		var allDirs []string
		for _, ad := range adapters {
			allDirs = append(allDirs, dirName(ad.SourcePath))
		}
		for _, ad := range adapters {
			allDirs = append(allDirs, dirName(ad.PlanPath))
		}
		commonRoot := commonDirPath(allDirs)
		af("*(Source paths below use the source domain's Oracle home,\n"+
			"`%s`\n(or a parent of it) — substitute your target Oracle\n"+
			"home if the `.rar`/plan files are staged at a different path on "+
			"the target\nhost.)*\n", commonRoot)
		for i, ad := range adapters {
			a(renderAdapterDetailed(i+1, ad))
		}
		a("---\n")
		a("## ➡ End of Phase 6\n")
		a("- [ ] Click **Activate Changes**.")
		af("- [ ] Verify: **Deployments** shows %s all as **Active**.",
			joinBacktickNamesFromAdapters(adapters))
		a("- [ ] For each adapter, open **Testing** or **Monitoring** and " +
			"confirm each\n      connection instance you configured above " +
			"resolves successfully.\n")
		a("---\n")
	}

	// ---- Full verification, rollback, gaps ----
	sectionNum := 7
	if len(adapters) > 0 {
		sectionNum = 8
	}
	af("# %d. Full Post-Release Verification\n", sectionNum)
	a("Go through every row below in order — do not skip any even if an " +
		"earlier\nphase's own checklist already covered part of it.\n")
	step := 1
	var dsCheckLine string
	if len(untargetedDS) > 0 {
		dsCheckLine = fmt.Sprintf("Success for the %d targeted ones; %s just needs to be\n       "+
			"present (untargeted, can't be tested this way).",
			len(targetedDS), joinBacktickNamesFromDS(untargetedDS))
	} else {
		dsCheckLine = "Success for all of them."
	}
	af("%d. [ ] **Data Sources:** each of the %d → Monitoring → Testing → "+
		"Test.\n       %s", step, len(dsList), dsCheckLine)
	step++
	af("%d. [ ] **Persistent Stores:** all %d present in the list with "+
		"correct\n       targets.", step, len(stores))
	step++
	af("%d. [ ] **JMS Servers:** all %d show Health = OK under Monitoring.",
		step, len(jmsServers))
	step++
	af("%d. [ ] **JMS runtime bindings:** Environment → Servers → *each "+
		"server* →\n       **View JNDI Tree** — confirm every `jms/...` "+
		"name from Phase 5\n       appears bound.", step)
	step++
	af("%d. [ ] **SAF Agents:** all %d show up under Monitoring with the "+
		"correct\n       Logging setting.", step, len(safAgents))
	step++
	if len(defaultCFs) > 0 {
		af("%d. [ ] **Connection Factory targeting:** %s — each shows "+
			"**Default\n       Targeting** on its Targets tab (no "+
			"subdeployment).", step, joinBacktickNames(defaultCFs))
		step++
	}
	if len(adapters) > 0 {
		af("%d. [ ] **Adapters:** all %d show **Active** under "+
			"Deployments.", step, len(adapters))
		step++
		totalCI := totalConnectionInstances(adapters)
		af("%d. [ ] **Adapter connection instances:** all %d present under "+
			"their\n       respective Outbound Connection Pools and testing "+
			"OK.", step, totalCI)
		step++
	}
	a("")
	a("---\n")

	af("# %d. Rollback\n", sectionNum+1)
	a("- **Within a phase, before Activate Changes:** Change Center → " +
		"**Undo All\n  Changes**. This discards everything staged in the " +
		"current edit session.")
	a("- **After Activate Changes:** delete the objects created in that " +
		"phase, in\n  reverse creation order, or restore the pre-change " +
		"config backup taken in\n  §0.")
	a("- Objects created by this plan are additive and don't touch " +
		"existing\n  config, so a partial rollback is low-risk — the only " +
		"danger is if you\n  target something new over an existing object " +
		"with the same name, which\n  none of these object names should " +
		"collide with on a clean target domain.\n")
	a("---\n")

	af("# %d. Known Gaps — Confirm Before Go-Live\n", sectionNum+2)
	a("| # | Item | What to do |")
	a("|---|---|---|")
	gnum := 1
	if len(dsList) > 0 {
		af("| %d | %d JDBC passwords | None were exported — get from "+
			"vault/DBA before Phase 1's post-steps. |", gnum, len(dsList))
		gnum++
	}
	for _, dep := range extDeps {
		af("| %d | `%s` | Must already exist on target — referenced by "+
			"persistent store `%s` (Phase 2). |", gnum, dep.DSName, dep.StoreName)
		gnum++
	}
	if len(adapters) > 0 {
		af("| %d | Adapter connection-instance credentials | Baked into "+
			"each plan XML, not exported — review/set all %d instances in "+
			"Phase 6 before go-live. |", gnum, totalConnectionInstances(adapters))
		gnum++
		af("| %d | Adapter source/plan paths | Substitute your target "+
			"Oracle home for the source paths throughout Phase 6. |", gnum)
		gnum++
	}
	if len(untargeted) > 0 {
		af("| %d | Untargeted SAF agents | %s — confirm with the app owner "+
			"this is intentional, not an oversight, before matching it "+
			"here. |", gnum, joinBacktickNames(untargeted))
		gnum++
	}
	af("| %d | Target infrastructure names | If your target domain's %s "+
		"differ, substitute your names everywhere those appear in this plan "+
		"-- everything else (object names) must be created exactly as "+
		"written. |", gnum, joinBacktickNames(targetNames))

	return b.String()
}

// ---- small join helpers over typed slices (mirrors the Python
// generator expressions like ", ".join("`%s`" % d["name"] for d in ds_list)) ----

func joinBacktickNamesFromDS(ds []JdbcDataSource) string {
	names := make([]string, 0, len(ds))
	for _, d := range ds {
		names = append(names, d.Name)
	}
	return joinBacktickNames(names)
}

func joinBacktickNamesFromStores(stores []PersistentStore) string {
	names := make([]string, 0, len(stores))
	for _, s := range stores {
		names = append(names, s.Name)
	}
	return joinBacktickNames(names)
}

func joinBacktickNamesFromJmsServers(servers []JmsServer) string {
	names := make([]string, 0, len(servers))
	for _, s := range servers {
		names = append(names, s.Name)
	}
	return joinBacktickNames(names)
}

func joinBacktickNamesFromSaf(agents []SafAgent) string {
	names := make([]string, 0, len(agents))
	for _, s := range agents {
		names = append(names, s.Name)
	}
	return joinBacktickNames(names)
}

func joinBacktickNamesFromAdapters(adapters []AdapterDeployment) string {
	names := make([]string, 0, len(adapters))
	for _, ad := range adapters {
		names = append(names, ad.Name)
	}
	return joinBacktickNames(names)
}

// ---------------------------------------------------------------------------
// Per-object detailed renderers (1:1 with the _render_*_detailed functions
// in gen_release_plan.py).
// ---------------------------------------------------------------------------

func renderDatasourceDetailed(i int, ds JdbcDataSource) string {
	b := &builder{}
	a := b.a
	af := b.af

	host, port, dbname := connFields(ds)
	props := ds.DriverProperties
	drv, ok := DriverInfo[ds.DriverName]
	if !ok {
		drv = driverInfo{dbType: "*(unrecognised driver -- pick manually)*", label: ds.DriverName}
	}
	txStep, ok := TxProtocolSteps[ds.GlobalTransactionsProtocol]
	if !ok {
		txStep = fmt.Sprintf("set per the source's Tx Protocol value: `%s`", ds.GlobalTransactionsProtocol)
	}
	jndi := strings.Join(ds.JndiNames, "; ")

	af("## 1.%d Data Source: `%s`\n", i, ds.Name)
	a("**Wizard:**")
	a("1. [ ] Domain Structure (left tree) → **Services → Data Sources**.")
	a("2. [ ] Click **New → Generic Data Source**.")
	a("3. [ ] Page \"Create a New JDBC Data Source\":")
	af("   - Name: `%s`", ds.Name)
	af("   - JNDI Name: `%s`", jndi)
	af("   - Database Type: **%s**", drv.dbType)
	a("   - Click **Next**.")
	af("4. [ ] Page \"Database Driver\": choose the driver matching "+
		"`%s`\n       — **%s**. Click **Next**.", ds.DriverName, drv.label)
	af("5. [ ] Page \"Transaction Options\": %s. Click **Next**.", txStep)
	a("6. [ ] Page \"Connection Properties\": enter (these only assemble a " +
		"URL the\n       wizard shows you next — you will overwrite it in " +
		"the Post-Step):")
	if dbname != "" {
		af("   - Database Name: `%s`", dbname)
	}
	if host != "" {
		af("   - Host Name: `%s`", host)
	}
	if port != "" {
		af("   - Port: `%s`", port)
	}
	if u := dbUser(ds); u != "" {
		af("   - Database User Name: `%s`", u)
	}
	a("   - Password / Confirm Password: leave blank for now (set in " +
		"Post-Step).")
	a("   - Click **Next**.")
	a("7. [ ] Page \"Test Database Connection\": ignore the assembled URL " +
		"shown\n       here — you do not need to click Test Configuration " +
		"(it will fail\n       with no password). Click **Next**.")
	if len(ds.Targets) > 0 {
		af("8. [ ] Page \"Select Targets\": tick %s. Click **Finish**.", fmtTargets(ds.Targets))
	} else {
		a("8. [ ] Page \"Select Targets\": **tick nothing** — this data " +
			"source is\n       untargeted on the source domain. Click " +
			"**Finish**.")
	}
	a("\n**Post-Step (open the data source you just created → " +
		"Configuration tab):**")
	a("9. [ ] **Connection Pool** sub-tab — set:")
	af("   - URL: `%s`", ds.URL)
	af("   - Driver Class Name: `%s`", ds.DriverName)
	af("   - Properties: %s", driverPropsJoined(props))
	a("   - Password: ⚠️ **obtain from vault/DBA** — set here and in " +
		"Confirm Password.")
	af("   - Initial Capacity: `%s`", pyInt(ds.InitialCapacity))
	af("   - Maximum Capacity: `%s`", pyInt(ds.MaxCapacity))
	af("   - Minimum Capacity: `%s`", pyInt(ds.MinCapacity))
	a("10. [ ] **Connection Pool → Advanced** (expand the Advanced link):")
	af("   - Test Table Name: `%s`", ds.TestTableName)
	af("   - Test Connections On Reserve: **%s**",
		ternary(ds.TestConnectionsOnReserve, "checked (Yes)", "unchecked (No)"))
	a("11. [ ] Click **Save**.\n")
	return b.joinRaw()
}

func renderFilestoreDetailed(phase, num int, store PersistentStore) string {
	b := &builder{}
	a := b.a
	af := b.af

	af("## %d.%d File Store: `%s`\n", phase, num, store.Name)
	a("1. [ ] **Services → Persistent Stores → New → Create FileStore**.")
	af("2. [ ] Name: `%s`. Target: %s. Click **OK**.",
		store.Name, fmtTargets(store.Targets))
	a("3. [ ] Open the store you just created.")
	if store.Directory != nil && *store.Directory != "" {
		af("4. [ ] Set **Directory**: `%s`.", *store.Directory)
	} else {
		a("4. [ ] Leave **Directory** at its default (blank).")
	}
	sync := "*(default)*"
	if store.SynchronousWritePolicy != nil && *store.SynchronousWritePolicy != "" {
		sync = *store.SynchronousWritePolicy
	}
	af("5. [ ] Expand **Advanced** → set **Synchronous Write Policy** to "+
		"**%s**.", sync)
	a("6. [ ] Click **Save**.\n")
	return b.joinRaw()
}

func renderJdbcstoreDetailed(phase, num int, store PersistentStore, needsPreExistingDep bool) string {
	b := &builder{}
	a := b.a
	af := b.af

	af("## %d.%d JDBC Store: `%s`\n", phase, num, store.Name)
	a("1. [ ] **Services → Persistent Stores → New → Create JDBCStore**.")
	af("2. [ ] Name: `%s`.", store.Name)
	hasMigratable := false
	for _, t := range store.Targets {
		if strings.Contains(t, "(migratable)") {
			hasMigratable = true
		}
	}
	if len(store.Targets) > 0 && hasMigratable {
		af("3. [ ] Target: click the target picker and select the "+
			"**migratable target**\n       entry named **`%s`** — not the "+
			"plain server entry.", strings.Join(store.Targets, ", "))
	} else {
		af("3. [ ] Target: %s.", fmtTargets(store.Targets))
	}
	depNote := ""
	if needsPreExistingDep {
		depNote = " ⚠️ — this must already exist on the target (referenced " +
			"but not exported by this extract; confirm before " +
			"proceeding)."
	}
	af("4. [ ] Data Source: **`%s`**%s", pyStr(store.DataSource), depNote)
	if store.PrefixName != nil && *store.PrefixName != "" {
		a("5. [ ] Click **OK**.")
		af("6. [ ] Open the store you just created → set **Prefix Name**: "+
			"`%s`.", *store.PrefixName)
		a("7. [ ] Click **Save**.\n")
	} else {
		a("5. [ ] Prefix Name: leave blank (none specified for this " +
			"store).")
		a("6. [ ] Click **OK**, then **Save** if prompted.\n")
	}
	return b.joinRaw()
}

func renderModuleDetailed(i int, mod JmsModule) string {
	b := &builder{}
	a := b.a
	af := b.af

	af("## 5.%d Module: `%s`\n", i, mod.Name)
	a("**Create the module:**")
	a("1. [ ] **Services → Messaging → JMS Modules → New**.")
	af("2. [ ] Name: `%s`. Click **Next**.", mod.Name)
	af("3. [ ] Targets: %s. Click **Next**, then **Finish**.\n", fmtTargets(mod.Targets))

	step := 4
	nextStep := func() int {
		s := step
		step++
		return s
	}

	for _, sub := range mod.Subdeployments {
		af("**Add subdeployment `%s`:**", sub.Name)
		af("%d. [ ] Open the module → **Subdeployments** tab → **New**.", nextStep())
		af("%d. [ ] Subdeployment Name: `%s`. Click **Next**.", nextStep(), sub.Name)
		af("%d. [ ] Targets: %s. Click **Finish**.\n", nextStep(), fmtTargets(sub.Targets))
	}

	destBlock := func(items []Destination, label, kind string, needsLB bool) {
		for _, item := range items {
			af("**Add %s `%s`:**", label, item.Name)
			af("%d. [ ] Open the module → **New** → select **%s**. Click "+
				"**Next**.", nextStep(), kind)
			af("%d. [ ] Name: `%s`. JNDI Name: `%s`. Click **Next**.",
				nextStep(), item.Name, item.JNDI)
			af("%d. [ ] Subdeployment: `%s`. Click **Finish**.",
				nextStep(), item.Subdeployment)
			if needsLB && item.LoadBalancingPolicy != nil && *item.LoadBalancingPolicy != "" {
				af("%d. [ ] Open the new destination → set **Load "+
					"Balancing Policy** to\n       **%s**. Save.\n",
					nextStep(), *item.LoadBalancingPolicy)
			} else {
				a("")
			}
		}
	}

	destBlock(mod.Queues, "queue", "Queue", false)
	destBlock(mod.UniformDistributedQueues, "uniform distributed queue", "Distributed Queue → Uniform", true)
	destBlock(mod.DistributedQueues, "distributed queue", "Distributed Queue", true)
	destBlock(mod.Topics, "topic", "Topic", false)
	destBlock(mod.UniformDistributedTopics, "uniform distributed topic", "Distributed Topic → Uniform", true)
	destBlock(mod.DistributedTopics, "distributed topic", "Distributed Topic", true)

	modTargets := mod.Targets
	inheritDesc := "inherits the module's target"
	if len(modTargets) > 0 {
		inheritDesc = "inherits " + joinBacktickNames(modTargets)
	}
	for _, cf := range mod.ConnectionFactories {
		suffix := ""
		if cf.DefaultTargetingEnabled {
			suffix = fmt.Sprintf(" (default targeting -- %s)", inheritDesc)
		}
		af("**Add its Connection Factory `%s`%s:**", cf.Name, suffix)
		af("%d. [ ] Open the module → **New** → select **Connection "+
			"Factory**. Click\n       **Next**.", nextStep())
		af("%d. [ ] Name: `%s`. JNDI Name: `%s`. Click **Next**.",
			nextStep(), cf.Name, cf.JNDI)
		if cf.DefaultTargetingEnabled {
			af("%d. [ ] On the Targeting page: leave **Default Targeting "+
				"Enabled** checked.\n       Do **not** select a "+
				"subdeployment (this CF %s). Click **Finish**.\n", nextStep(), inheritDesc)
		} else {
			af("%d. [ ] On the Targeting page: select subdeployment `%s`. "+
				"Click **Finish**.\n", nextStep(), pyStr(cf.Subdeployment))
		}
	}

	for _, eh := range mod.SafErrorHandlings {
		af("**Add its SAF Error Handling `%s`:**", eh.Name)
		af("%d. [ ] Open the module → **New** → select **SAF Error "+
			"Handling**. Click\n       **Next**.", nextStep())
		af("%d. [ ] Name: `%s`.", nextStep(), eh.Name)
		af("%d. [ ] Policy: **%s**. Click **Finish**.\n", nextStep(), eh.Policy)
	}

	for _, t := range mod.Templates {
		af("**Note — Template `%s`** (create via New → JMS Template if the "+
			"target domain doesn't already inherit one): Redelivery Delay "+
			"`%s`, Redelivery Limit `%s`, TTL `%s`, Priority `%s`.\n",
			t.Name, pyInt(t.RedeliveryDelay), pyInt(t.RedeliveryLimit), pyInt(t.TimeToLive), pyInt(t.Priority))
	}

	for _, q := range mod.Quotas {
		af("**Note — Quota `%s`:** Bytes Max `%s`, Messages Max `%s`, "+
			"Policy `%s`, Shared: %s.\n",
			q.Name, pyInt(q.BytesMaximum), pyInt(q.MessagesMaximum), q.Policy, boolYesNo(q.Shared))
	}

	for _, dk := range mod.DestinationKeys {
		af("**Note — Destination Key `%s`:** Property `%s`, Key Type `%s`, "+
			"Direction `%s`.\n", dk.Name, dk.Property, dk.KeyType, dk.Direction)
	}

	for _, fs := range mod.ForeignServers {
		af("**Note — Foreign Server `%s`:** Initial Context Factory `%s`, "+
			"Connection URL `%s`, Default Targeting: %s.",
			fs.Name, fs.InitialContextFactory, fs.ConnectionURL, boolYesNo(fs.DefaultTargetingEnabled))
		for _, fd := range fs.ForeignDestinations {
			af("- Foreign Destination `%s`: local JNDI `%s` → remote JNDI "+
				"`%s`.", fd.Name, fd.LocalJNDIName, fd.RemoteJNDIName)
		}
		for _, fcf := range fs.ForeignConnectionFactories {
			af("- Foreign Connection Factory `%s`: local JNDI `%s` → "+
				"remote JNDI `%s`.", fcf.Name, fcf.LocalJNDIName, fcf.RemoteJNDIName)
		}
		a("")
	}

	return b.joinRaw()
}

func renderAdapterDetailed(i int, ad AdapterDeployment) string {
	b := &builder{}
	a := b.a
	af := b.af

	af("## 6.%d Adapter: `%s`\n", i, ad.Name)
	af("1. [ ] **Deployments → Install** (or select the existing `%s` →\n"+
		"       **Update**, if one already exists from the domain template "+
		"and you\n       are replacing its plan).", ad.Name)
	af("2. [ ] Browse to the source `.rar`: `%s`. Click **Next**.", ad.SourcePath)
	a("3. [ ] Choose **Install this deployment as an application** (or, " +
		"if\n       updating, proceed with the update flow). Click " +
		"**Next**.")
	af("4. [ ] Targets: tick %s. Click **Next**.", fmtTargets(ad.Targets))
	af("5. [ ] Deployment Plan path: `%s`. Click **Finish**.", ad.PlanPath)
	cis := ad.ConnectionInstances
	plural := "below"
	desc := "this connection instance"
	if len(cis) != 1 {
		desc = fmt.Sprintf("each of these %d connection instances", len(cis))
	}
	af("6. [ ] Open the deployed `%s` → **Configuration → Outbound\n"+
		"       Connection Pools**. Review/set host, port, user, password "+
		"for %s\n       %s:", ad.Name, desc, plural)
	for _, ci := range cis {
		af("   - [ ] `%s`", ci)
	}
	a("7. [ ] Save each change, and click **Update Plan** if the console " +
		"prompts\n       you to persist the edit into the plan XML.\n")
	return b.joinRaw()
}

func ternary(cond bool, ifTrue, ifFalse string) string {
	if cond {
		return ifTrue
	}
	return ifFalse
}
