package main

import (
	"fmt"
	"strings"
)

// render_condensed.go — direct port of render_condensed() and
// _render_module_child_tables() from gen_release_plan.py. Procedure once,
// then data tables — mirrors the structure of the original hand-written
// gmx/dev/release-plan.md.

type builder struct {
	lines []string
}

func (b *builder) a(s string) {
	b.lines = append(b.lines, s)
}

func (b *builder) af(format string, args ...interface{}) {
	b.a(fmt.Sprintf(format, args...))
}

func (b *builder) String() string {
	return strings.Join(b.lines, "\n") + "\n"
}

// joinRaw mirrors Python's plain "\n".join(out) (no trailing newline) --
// used by sub-renderers whose output is appended as a SINGLE element into
// a parent builder (the parent's own "\n".join adds the separator; adding
// a trailing newline here as well would double it, unlike the top-level
// document renderers which own their own final "\n").
func (b *builder) joinRaw() string {
	return strings.Join(b.lines, "\n")
}

func renderCondensed(e *Export, domain, env string) string {
	infra := e.Infrastructure
	dsList := infra.JdbcDataSources
	stores := infra.PersistentStores
	fStores := fileStores(e)
	jStores := jdbcStores(e)
	jmsServers := infra.JmsServers
	safAgents := e.SafAgents
	modules := e.JmsModules
	adapters := e.AdapterDeployments

	b := &builder{}
	a := b.a
	af := b.af

	a("# Release Plan — SOA Suite Domain JMS / Infrastructure Rebuild\n")
	af("**Domain / Environment:** `%s` / `%s`", domain, env)
	a("**Source of values:** `export.json` (generated by `extract_objects.py`)")
	a("**Target:** WebLogic Admin Console (manual deployment)")
	a("**Generated by:** `gorelease` (Go port of `extract/gen_release_plan.py`) -- re-run against a " +
		"fresh export if the source domain's config changes.\n")
	a("---\n")

	a("## 1. Purpose & Scope\n")
	a("This plan recreates, on a target WebLogic/SOA Suite domain, the JMS and\n" +
		"supporting infrastructure configuration captured from the source domain:\n")
	af("- %d JDBC data sources", len(dsList))
	af("- %d persistent stores (%d file, %d JDBC)", len(stores), len(fStores), len(jStores))
	af("- %d JMS servers", len(jmsServers))
	af("- %d SAF (Store-and-Forward) agents", len(safAgents))
	af("- %d JMS modules with their subdeployments, destinations and connection factories", len(modules))
	af("- %d adapter deployments (redeploy + plan)\n", len(adapters))
	a("**Out of scope:** SOA composites, OSB projects, system/internal " +
		"objects (these\nbelong to the domain template / product install).\n")
	a("---\n")

	a("## 2. Prerequisites (complete before starting)\n")
	a("| # | Item | Notes |")
	a("|---|---|---|")
	a("| 2.1 | Admin Console URL + credentials | `http://<admin-host>:<port>/console` |")
	targetNames := infraTargetNames(e)
	af("| 2.2 | Managed servers / clusters exist | %s (or target-domain equivalents) |",
		joinBacktickNames(targetNames))
	if len(dsList) > 0 {
		af("| 2.3 | Database passwords | ⚠️ %d data-source passwords — obtain "+
			"from vault / DBA (see §5 table) |", len(dsList))
	}
	extDeps := externalStoreDependencies(e)
	for i, dep := range extDeps {
		af("| 2.4.%d | `%s` present | Referenced by `%s`; not in this "+
			"extract -- confirm it exists on target |", i+1, dep.DSName, dep.StoreName)
	}
	if len(adapters) > 0 {
		a("| 2.5 | Adapter `.rar` + plan files staged | On a path reachable by the target domain (see §11) |")
	}
	a("| 2.6 | Change of target names? | If server/cluster names differ on " +
		"target, note the mapping and substitute throughout |")
	a("| 2.7 | Backup | Take a config backup / snapshot of the target domain " +
		"before changes |\n")

	af("**Naming substitution:** wherever this plan uses %s,\n"+
		"substitute the target-domain name if it differs. All other object names (data "+
		"sources,\nstores, modules, queues) should be created **exactly as "+
		"written** — applications look\nthem up by name/JNDI.\n", joinBacktickNames(targetNames))
	a("---\n")

	a("## 3. Login & Edit Session\n")
	a("Perform once at the start; keep the session for a whole phase, then " +
		"activate.\n")
	a("1. Browse to `http://<admin-host>:<port>/console`.")
	a("2. Log in with the admin account.")
	a("3. In the **Change Center** (top-left), click **Lock & Edit**.")
	a("   - All changes below are staged until you click **Activate Changes**.")
	a("4. At the end of each phase, click **Activate Changes**.")
	a("   - If a phase reports errors, use **Undo All Changes** and resolve " +
		"before retrying.\n")
	a("> **Discipline:** activate at the end of each phase (not each object). " +
		"This keeps\n> related changes atomic and makes rollback per-phase " +
		"clean.\n")
	a("---\n")

	a("## 4. Execution Order (dependency chain)\n")
	a("Do the phases strictly in order — later objects reference earlier " +
		"ones:\n")
	a("```")
	a("Phase 1  JDBC Data Sources         (referenced by JDBC stores, adapters)")
	a("Phase 2  Persistent Stores         (file + JDBC; reference data sources)")
	a("Phase 3  JMS Servers               (reference persistent stores)")
	a("Phase 4  SAF Agents                (reference persistent stores)")
	a("Phase 5  JMS Modules + children    (reference JMS servers / SAF agents via subdeployments)")
	a("Phase 6  Adapter Deployments       (reference data sources, JMS resources)")
	a("```\n")
	a("---\n")

	// ---- Phase 1: data sources ----
	a("## 5. Phase 1 — JDBC Data Sources\n")
	a("### Procedure (repeat for each data source in the table)\n")
	a("1. **Domain Structure → Services → Data Sources**.")
	a("2. Click **New → Generic Data Source**.")
	a("3. **Page 1:** Name / JNDI Name as per table; Database Type per " +
		"driver family; click **Next**.")
	a("4. **Page 2 (Database Driver):** pick the driver matching the " +
		"**Driver Class** in the table. Click **Next**.")
	a("5. **Page 3 (Transaction Options):** set per the **Tx Protocol** " +
		"column. Click **Next**.")
	a("6. **Page 4 (Connection Properties):** enter database name/host/port/" +
		"user/password as best matches. Click **Next**.")
	a("7. **Page 5 (Test):** ignore the assembled URL — it will be " +
		"overwritten. Click **Next**.")
	a("8. **Page 6 (Targets):** tick the targets from the table. Click " +
		"**Finish**.")
	a("9. **Post-step:** open **Configuration → Connection Pool** and set " +
		"URL / Driver Class Name / Properties / Password exactly as the " +
		"table, plus **Advanced** Test Table Name and Test Connections On " +
		"Reserve, plus Initial/Max/Min capacity.\n")
	a("### Data\n")
	af("> ⚠️ = password required from vault/DBA. None of the %d passwords "+
		"were exported.\n", len(dsList))
	for i, ds := range dsList {
		host, port, dbname := connFields(ds)
		_ = dbname
		_ = host
		_ = port
		props := ds.DriverProperties
		drv := DriverInfo[ds.DriverName]
		af("#### 5.%d %s", i+1, ds.Name)
		a("| Field | Value |")
		a("|---|---|")
		af("| Name / JNDI | `%s` / `%s` |", ds.Name, strings.Join(ds.JndiNames, "; "))
		af("| Driver Class | `%s` |", ds.DriverName)
		af("| Tx Protocol | %s |", ds.GlobalTransactionsProtocol)
		af("| URL | `%s` |", ds.URL)
		af("| Properties | %s |", driverPropsJoined(props))
		a("| Password | ⚠️ |")
		af("| Test Table | `%s` · Test on Reserve: **%s** |",
			ds.TestTableName, boolYesNo(ds.TestConnectionsOnReserve))
		af("| Capacity (init/max/min) | %s / %s / %s |",
			pyInt(ds.InitialCapacity), pyInt(ds.MaxCapacity), pyInt(ds.MinCapacity))
		af("| Targets | %s |\n", fmtTargets(ds.Targets))
		_ = drv
	}
	af("**➡ Activate Changes. Verify:** each data source shows on the Data " +
		"Sources list;\nfor targeted ones, Monitoring → Testing → **Test Data " +
		"Source** returns success\n(requires correct password).\n")
	a("---\n")

	// ---- Phase 2: persistent stores ----
	a("## 6. Phase 2 — Persistent Stores\n")
	a("### 6a. File Stores\n")
	a("**Procedure (repeat per row):**")
	a("1. **Services → Persistent Stores → New → Create FileStore**.")
	a("2. **Name:** per table. **Target:** per table.")
	a("3. Open the store → set **Directory** (if specified) and **Advanced " +
		"→ Synchronous Write Policy** per table. Save.\n")
	a("| Name | Directory | Sync Policy | Target |")
	a("|---|---|---|---|")
	for _, s := range fStores {
		dir := "*(default/blank)*"
		if s.Directory != nil && *s.Directory != "" {
			dir = fmt.Sprintf("`%s`", *s.Directory)
		}
		sync := "*(default)*"
		if s.SynchronousWritePolicy != nil && *s.SynchronousWritePolicy != "" {
			sync = *s.SynchronousWritePolicy
		}
		target := "*(none)*"
		if len(s.Targets) > 0 {
			target = strings.Join(s.Targets, ", ")
		}
		af("| `%s` | %s | %s | `%s` |", s.Name, dir, sync, target)
	}
	a("")
	a("### 6b. JDBC Stores\n")
	a("**Procedure (repeat per row):**")
	a("1. **Services → Persistent Stores → New → Create JDBCStore**.")
	a("2. **Name / Target / Data Source:** per table.")
	a("3. If **Prefix** is given, open the store and set **Prefix Name**. " +
		"Save.\n")
	a("| Name | Data Source | Prefix | Target |")
	a("|---|---|---|---|")
	extDepNames := extDepNamesOnly(extDeps)
	hasMigratable := false
	for _, s := range jStores {
		dsNote := pyStr(s.DataSource)
		if extDepNames[s.Name] {
			dsNote += " *(system DS — must pre-exist)*"
		}
		prefix := "*(none)*"
		if s.PrefixName != nil && *s.PrefixName != "" {
			prefix = fmt.Sprintf("`%s`", *s.PrefixName)
		}
		af("| `%s` | `%s` | %s | `%s` |", s.Name, dsNote, prefix, strings.Join(s.Targets, ", "))
		for _, t := range s.Targets {
			if strings.Contains(t, "(migratable)") {
				hasMigratable = true
			}
		}
	}
	a("")
	if hasMigratable {
		a("> For the `(migratable)` targets, select the migratable target " +
			"entry from the\n> target picker (e.g. as listed above), not the " +
			"plain server.\n")
	}
	af("**➡ Activate Changes. Verify:** all %d stores appear on the "+
		"Persistent Stores list\nwith the correct targets.\n", len(stores))
	a("---\n")

	// ---- Phase 3: JMS servers ----
	a("## 7. Phase 3 — JMS Servers\n")
	a("**Procedure (repeat per row):**")
	a("1. **Services → Messaging → JMS Servers → New**.")
	a("2. **Name:** per table. **Persistent Store:** select per table. " +
		"Click **Next**.")
	a("3. **Target:** per table. Click **Finish**.")
	a("4. (Byte/message maxima are unlimited — leave defaults.)\n")
	a("| Name | Persistent Store | Target |")
	a("|---|---|---|")
	for _, js := range jmsServers {
		af("| `%s` | `%s` | `%s` |", js.Name, js.PersistentStore, strings.Join(js.Targets, ", "))
	}
	a("")
	af("**➡ Activate Changes. Verify:** %d JMS servers listed, each bound to "+
		"its store,\nhealth OK after the next server restart (or immediately "+
		"if dynamically deployed).\n", len(jmsServers))
	a("---\n")

	// ---- Phase 4: SAF agents ----
	a("## 8. Phase 4 — SAF Agents\n")
	a("**Procedure (repeat per row):**")
	a("1. **Services → Messaging → Store-and-Forward Agents → New**.")
	a("2. **Name:** per table. **Persistent Store:** select per table. " +
		"**Agent Type:** per table. Click **Next**.")
	a("3. **Target:** per table. Click **Finish**.")
	a("4. Open the agent → confirm/set the defaults below.\n")
	if len(safAgents) > 0 {
		s0 := safAgents[0]
		logging := "DISABLED"
		if s0.LoggingEnabled {
			logging = "ENABLED"
		}
		af("**Common settings (all agents):** Retry Delay Base = %s ms · "+
			"Retry Delay Max = %s ms · Retry Multiplier = %s · Acknowledge "+
			"Interval = %s · Window Size = %s · Time-To-Live = %s · "+
			"**Logging = %s**.\n",
			pyInt(s0.RetryDelayBase), pyInt(s0.RetryDelayMaximum),
			pyInt(s0.RetryDelayMultiplier), pyInt(s0.AcknowledgeInterval),
			pyInt(s0.WindowSize), pyInt(s0.TimeToLive), logging)
	}
	a("| Name | Agent Type | Store | Target |")
	a("|---|---|---|---|")
	for _, s := range safAgents {
		target := "*(none — leave untargeted)*"
		if len(s.Targets) > 0 {
			target = strings.Join(s.Targets, ", ")
		}
		af("| `%s` | %s | `%s` | %s |", s.Name, s.ServiceType, s.Store, target)
	}
	a("")
	untargeted := untargetedSafAgents(e)
	if len(untargeted) > 0 {
		agentWord := "Agents are"
		if len(untargeted) == 1 {
			agentWord = "Agent is"
		}
		af("> %s untargeted on the source (%s).\n> Recreate as untargeted to "+
			"match; confirm with the app owner whether this is intended\n> "+
			"before go-live.\n", agentWord, joinBacktickNames(untargeted))
	}
	a("**➡ Activate Changes.**\n")
	a("---\n")

	// ---- Phase 5: JMS modules ----
	a("## 9. Phase 5 — JMS Modules\n")
	a("For each module: create the module + targets, add **subdeployments " +
		"first**, then\ndestinations, then connection factories, then SAF " +
		"error handlings.\n")
	a("### Generic procedures\n")
	a("**Create a module:**")
	a("1. **Services → Messaging → JMS Modules → New**.")
	a("2. **Name:** per module heading. Click **Next**.")
	a("3. **Targets:** tick the module target. Click **Next**, then " +
		"**Finish**.\n")
	a("**Add a subdeployment:**")
	a("1. Open the module → **Subdeployments** tab → **New**.")
	a("2. **Subdeployment Name:** per table. Click **Next**.")
	a("3. **Targets:** tick the JMS server / SAF agent / cluster per table. " +
		"Click **Finish**.\n")
	a("**Add a queue / distributed queue / topic:**")
	a("1. Open the module → **New**.")
	a("2. Select the destination type per table. Click **Next**.")
	a("3. **Name** + **JNDI Name** per table. Click **Next**.")
	a("4. **Subdeployment:** select per table (this also sets the target). " +
		"Click **Finish**.")
	a("5. For distributed destinations, set **Load Balancing Policy** per " +
		"table after creation.\n")
	a("**Add a connection factory (default targeting):**")
	a("1. Open the module → **New → Connection Factory**. Click **Next**.")
	a("2. **Name** + **JNDI Name** per table. Click **Next**.")
	a("3. **Targeting:** leave **Default Targeting** enabled unless a " +
		"subdeployment is listed. Click **Finish**.\n")
	a("**Add a SAF error handling:**")
	a("1. Open the module → **New → SAF Error Handling**. Click **Next**.")
	a("2. **Name** per table, **Policy** per table. Click **Finish**.\n")
	a("---\n")

	for i, mod := range modules {
		af("### 9.%d %s  — target %s", i+1, mod.Name, joinBacktickNames(mod.Targets))
		subs := mod.Subdeployments
		if len(subs) > 0 {
			parts := make([]string, 0, len(subs))
			for _, s := range subs {
				parts = append(parts, fmt.Sprintf("`%s` → %s", s.Name, joinBacktickNames(s.Targets)))
			}
			a("**Subdeployments:** " + strings.Join(parts, "; "))
		}
		renderModuleChildTables(b, mod, mod.Targets)
		if mod.childCount() == 0 && len(subs) == 0 {
			a("*(no children captured for this module)*")
		}
		a("")
	}
	a("**➡ Activate Changes. Verify:** each module lists its " +
		"subdeployments and resources;\ndefault-targeted connection " +
		"factories show **Default Targeting** on their Targets tab\n(no " +
		"subdeployment).\n")
	a("---\n")

	// ---- Phase 6: adapters ----
	if len(adapters) > 0 {
		a("## 10. Phase 6 — Adapter Deployments\n")
		a("> Redeploy each adapter with its plan, then review " +
			"connection-instance content.\n> ⚠️ Connection-instance " +
			"credentials (host/user/password) live **inside the plan XML** " +
			"and were\n> **not exported** — they must be reviewed/updated " +
			"for the target after redeploy.\n")
		a("**Procedure (repeat per adapter):**")
		a("1. **Deployments → Install** (or select existing adapter → " +
			"**Update** to change the plan).")
		a("2. Browse to the **Source** `.rar` path (see table). Click " +
			"**Next**.")
		a("3. Choose **Install this deployment as an application** (or " +
			"update). Click **Next**.")
		a("4. Select **Targets** per table. Click **Next**.")
		a("5. Set the **Deployment Plan** path per table. Click " +
			"**Finish**.")
		a("6. Open the deployed adapter → **Configuration → Outbound " +
			"Connection Pools** →\n   expand each connection-instance JNDI " +
			"(below) → review/set host, port, user,\n   password for the " +
			"target environment. Save. Update the plan when prompted.\n")
		a("| Adapter | Source (.rar) | Plan | Targets |")
		a("|---|---|---|---|")
		for _, ad := range adapters {
			af("| `%s` | `%s` | `%s` | %s |", ad.Name, ad.SourcePath, ad.PlanPath, joinBacktickNames(ad.Targets))
		}
		a("\n**Connection instances per adapter (verify each after " +
			"redeploy):**\n")
		for _, ad := range adapters {
			af("- **%s:** %s", ad.Name, joinBacktickNames(ad.ConnectionInstances))
		}
		a("\n**➡ Activate Changes. Verify:** each adapter is **Active** " +
			"under Deployments;\nconnection instances resolve (Deployments " +
			"→ adapter → Testing / Monitoring).\n")
		a("---\n")
	}

	// ---- Verification & rollback & gaps ----
	a("## 11. Post-Release Verification\n")
	a("| # | Check | How |")
	a("|---|---|---|")
	a("| 11.1 | All data sources healthy | Data Sources → each → " +
		"Monitoring → Testing → Test |")
	af("| 11.2 | Persistent stores present | Persistent Stores list — %d "+
		"entries |", len(stores))
	a("| 11.3 | JMS servers running | JMS Servers → each → Monitoring " +
		"(Health = OK) |")
	a("| 11.4 | JMS runtime bindings | Environment → Servers → *server* → " +
		"View JNDI Tree — confirm each `jms/...` name is bound |")
	a("| 11.5 | SAF agents running | Store-and-Forward Agents → " +
		"Monitoring |")
	defaultCFs := defaultTargetedCFs(modules)
	if len(defaultCFs) > 0 {
		af("| 11.6 | CF default targeting | %s → Targets tab shows *Default "+
			"Targeting* |", joinBacktickNames(defaultCFs))
	}
	if len(adapters) > 0 {
		af("| 11.7 | Adapters active | Deployments — all %d adapters "+
			"*Active* |", len(adapters))
		a("| 11.8 | Adapter connection instances | Each adapter → Outbound " +
			"Connection Pools — instances present and test OK |")
	}
	a("")
	a("---\n")

	a("## 12. Rollback\n")
	a("- **Within a phase (before Activate):** Change Center → **Undo All " +
		"Changes**.")
	a("- **After Activate:** delete the objects created in that phase " +
		"(reverse order),\n  or restore the pre-change config backup taken " +
		"in step 2.7.")
	a("- Objects are additive and independent of existing config, so a " +
		"partial rollback\n  is low-risk provided nothing new was targeted " +
		"over an existing object of the\n  same name.\n")
	a("---\n")

	a("## 13. Known Gaps / Manual Items\n")
	a("| Item | Action |")
	a("|---|---|")
	if len(dsList) > 0 {
		af("| JDBC passwords (×%d) | Supply from vault during Phase 1 "+
			"post-step |", len(dsList))
	}
	for _, dep := range extDeps {
		af("| `%s` data source | Referenced by `%s` — must pre-exist on "+
			"target |", dep.DSName, dep.StoreName)
	}
	if len(adapters) > 0 {
		a("| Adapter connection-instance credentials | Review/update " +
			"inside plan XML after Phase 6 |")
		a("| Adapter source/plan paths | Substitute target Oracle home for " +
			"the source paths listed in §10 |")
	}
	if len(untargeted) > 0 {
		af("| Untargeted SAF agents | %s untargeted on source — confirm "+
			"intended |", joinBacktickNames(untargeted))
	}
	a("| Target names | Substitute if target domain uses different " +
		"server/cluster names |")
	a("")
	a("---\n")

	a("## 14. Extractor Warnings & Uncovered Objects\n")
	a("Fields the *extractor* captures but this plan cannot fully turn " +
		"into a click-through\nprocedure on its own -- read this section " +
		"even when Sections 1-13 look complete.\n")
	for _, line := range renderExtractorWarningsBody(e) {
		a(line)
	}

	return b.String()
}

func renderModuleChildTables(b *builder, mod JmsModule, moduleTargets []string) {
	a := b.a
	af := b.af

	if len(mod.Queues) > 0 {
		a("**Queues:**")
		a("| Name | JNDI | Subdeployment |")
		a("|---|---|---|")
		for _, q := range mod.Queues {
			af("| `%s` | `%s` | `%s` |", q.Name, q.JNDI, q.Subdeployment)
		}
	}
	if len(mod.UniformDistributedQueues) > 0 {
		a("**Uniform Distributed Queues:**")
		a("| Name | JNDI | Load Balancing | Subdeployment |")
		a("|---|---|---|---|")
		for _, q := range mod.UniformDistributedQueues {
			af("| `%s` | `%s` | `%s` | `%s` |", q.Name, q.JNDI, lbOrDefault(q.LoadBalancingPolicy), q.Subdeployment)
		}
	}
	if len(mod.DistributedQueues) > 0 {
		a("**Distributed Queues:**")
		a("| Name | JNDI | Load Balancing | Subdeployment |")
		a("|---|---|---|---|")
		for _, q := range mod.DistributedQueues {
			af("| `%s` | `%s` | `%s` | `%s` |", q.Name, q.JNDI, lbOrDefault(q.LoadBalancingPolicy), q.Subdeployment)
		}
	}
	if len(mod.Topics) > 0 {
		a("**Topics:**")
		a("| Name | JNDI | Subdeployment |")
		a("|---|---|---|")
		for _, t := range mod.Topics {
			af("| `%s` | `%s` | `%s` |", t.Name, t.JNDI, t.Subdeployment)
		}
	}
	if len(mod.UniformDistributedTopics) > 0 {
		a("**Uniform Distributed Topics:**")
		a("| Name | JNDI | Load Balancing | Subdeployment |")
		a("|---|---|---|---|")
		for _, t := range mod.UniformDistributedTopics {
			af("| `%s` | `%s` | `%s` | `%s` |", t.Name, t.JNDI, lbOrDefault(t.LoadBalancingPolicy), t.Subdeployment)
		}
	}
	if len(mod.DistributedTopics) > 0 {
		a("**Distributed Topics:**")
		a("| Name | JNDI | Load Balancing | Subdeployment |")
		a("|---|---|---|---|")
		for _, t := range mod.DistributedTopics {
			af("| `%s` | `%s` | `%s` | `%s` |", t.Name, t.JNDI, lbOrDefault(t.LoadBalancingPolicy), t.Subdeployment)
		}
	}
	if len(mod.ConnectionFactories) > 0 {
		a("**Connection Factories:**")
		a("| Name | JNDI | Targeting |")
		a("|---|---|---|")
		inheritDesc := "inherits module target"
		if len(moduleTargets) > 0 {
			inheritDesc = "inherits " + joinBacktickNames(moduleTargets)
		}
		for _, cf := range mod.ConnectionFactories {
			var targeting string
			if cf.DefaultTargetingEnabled {
				targeting = fmt.Sprintf("**Default targeting** (%s)", inheritDesc)
			} else {
				targeting = fmt.Sprintf("Subdeployment `%s`", pyStr(cf.Subdeployment))
			}
			af("| `%s` | `%s` | %s |", cf.Name, cf.JNDI, targeting)
		}
	}
	if len(mod.Templates) > 0 {
		a("**Templates:**")
		a("| Name | Redelivery Delay | Redelivery Limit | TTL | Priority |")
		a("|---|---|---|---|---|")
		for _, t := range mod.Templates {
			af("| `%s` | %s | %s | %s | %s |", t.Name, pyInt(t.RedeliveryDelay), pyInt(t.RedeliveryLimit), pyInt(t.TimeToLive), pyInt(t.Priority))
		}
	}
	if len(mod.Quotas) > 0 {
		a("**Quotas:**")
		a("| Name | Bytes Max | Messages Max | Policy | Shared |")
		a("|---|---|---|---|---|")
		for _, q := range mod.Quotas {
			af("| `%s` | %s | %s | %s | %s |", q.Name, pyInt(q.BytesMaximum), pyInt(q.MessagesMaximum), q.Policy, boolYesNo(q.Shared))
		}
	}
	if len(mod.DestinationKeys) > 0 {
		a("**Destination Keys:**")
		a("| Name | Property | Key Type | Direction |")
		a("|---|---|---|---|")
		for _, dk := range mod.DestinationKeys {
			af("| `%s` | %s | %s | %s |", dk.Name, dk.Property, dk.KeyType, dk.Direction)
		}
	}
	if len(mod.ForeignServers) > 0 {
		a("**Foreign Servers:**")
		for _, fs := range mod.ForeignServers {
			af("- `%s` — Initial Context Factory: `%s`, Connection URL: "+
				"`%s`, Default Targeting: %s",
				fs.Name, fs.InitialContextFactory, fs.ConnectionURL, boolYesNo(fs.DefaultTargetingEnabled))
			for _, fd := range fs.ForeignDestinations {
				af("  - Foreign Destination `%s`: local `%s` → remote `%s`", fd.Name, fd.LocalJNDIName, fd.RemoteJNDIName)
			}
			for _, fcf := range fs.ForeignConnectionFactories {
				af("  - Foreign Connection Factory `%s`: local `%s` → remote `%s`", fcf.Name, fcf.LocalJNDIName, fcf.RemoteJNDIName)
			}
		}
	}
	if len(mod.SafErrorHandlings) > 0 {
		a("**SAF Error Handlings:**")
		a("| Name | Policy |")
		a("|---|---|")
		for _, eh := range mod.SafErrorHandlings {
			af("| `%s` | `%s` |", eh.Name, eh.Policy)
		}
	}
}

func lbOrDefault(p *string) string {
	if p == nil || *p == "" {
		return "*(default)*"
	}
	return *p
}
